### ISSUE TITLE
No code example

### ISSUE THREAD

**Issue by Jhonatangiraldo** [forceofseth/route-guard#1]
## Description
I came here from [medium](https://blog.netcetera.com/how-to-create-guarded-routes-for-your-react-app-d2fe7c7b6122) link, her is supposed to have the code example. It's not a big deal, but the advice to make sure you push your changes so people learning about the topic can read it

**Comment by forceofseth** [comment]
Hi
My code is up to date you can see it here: https://github.com/forceofseth/route-guard/tree/master/src
